name: 'misc_gist'

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'action'  
  schedule:
    - cron:  '*/8 * * * *'

jobs:
  shell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - script: https://raw.githubusercontent.com/Eloco/Script-collect/main/misc/weather.sh
           if_skype: True
           skype_id: 19:d32d3d93d57740308986b42ec36e5525@thread.skype
           script_name: misc_gist
           skype_username : SKYPE_USERNAME
           skype_password : SKYPE_PASSWORD
           FILE_BASE: msg
           IF_PLAYWRIGHT: False
           repo_name  : Eloco/action-playwright-aws-md5
           repo_token : SEC_TOKEN
           gist_id : 3fd32567b6c8f6c79808905de208e59a

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          repository: '${{ matrix.repo_name  }}'
          token:      '${{ secrets[matrix.repo_token]  }}'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      - id: random-msg-path-generator
        run: echo "::set-output name=random::$(echo ${{ matrix.FILE_BASE }}/${RANDOM}.txt)"
        shell: bash

      - name: run bash script
        run: |
            curl $MATRIX_SCRIPT -o misc_script
            chmod +x misc_script
            mkdir ${{ matrix.FILE_BASE }}
            export command="bash misc_script"
            timeout 5m bash -c '$command || $command'  #retry command twice 
            sed -i '1i [GITHUB ACTION] <misc-gist-md5>' $FILE_PATH
            cat $FILE_PATH
        env:
            MATRIX_SCRIPT: ${{matrix.script}}
            FILE_PATH:     ${{steps.random-msg-path-generator.outputs.random}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fire
          #pip install pipreqs
          #pipreqs .
          #pip install -r requirements.txt

      - name: gist-read
        uses: sergeysova/gist-read-action@v1
        id: example-gist
        with:
          gist_id: ${{matrix.gist_id}}
          file_name: ${{matrix.script_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}

      - name: md5_count
        run: |
            wget https://raw.githubusercontent.com/Eloco/action-playwright-aws-md5/main/script/gist_md5.py
            echo "${{ steps.example-gist.outputs.content }}" > md5.txt
            files_num=`python gist_md5.py --file_md5="./md5.txt" --file_dir=${{ matrix.FILE_BASE }}`
            echo $files_num
            echo '::set-output name=FILE_NUM::'$files_num
            head md5.txt
        id: gist-md5

      - uses: popsiclestick/gist-sync-action@v1.2.0
        if  :  steps.gist-md5.outputs.FILE_NUM != '0'
        with:
          auth: ${{ secrets.SEC_TOKEN }}
          gist_url: https://gist.github.com/Eloco/${{matrix.gist_id}}
          gist_title: ${{matrix.script_name}}
          gist_description: ${{matrix.script_name}}
          github_file: md5.txt

      - name: send skype
        continue-on-error: true
        uses: Eloco/docker-action-send-skype@v2
        if  : steps.gist-md5.outputs.FILE_NUM != '0'
        with:
            skype_username : ${{ secrets[matrix.skype_username] }}
            skype_password : ${{ secrets[matrix.skype_password] }}
            skype_ids      : ${{ matrix.skype_id  }} 
            send_msg_path  : ${{ matrix.FILE_BASE }}
