name: 'fly_rescale'

on:
  #schedule:
  #- cron: '0 20 * * *' # every day
  workflow_dispatch:
jobs:
  rescale:
    name: rescale fly
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - fly: eloco-frp
        #- fly: eloco-frp-udp
        #- fly: eloco-dns
        #- fly: eloco-n2n
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: run scale
        run: |
            flyctl scale count 0 -a ${{ matrix.fly }}
            sleep 120
            flyctl scale count 1 -a ${{ matrix.fly }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
