name: gist-md5

on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: sergeysova/gist-read-action@v1
        id: example-gist
        with:
          gist_id: 51ecb4c20767e5326ba1a5323a42a631
          file_name: md5.txt
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}
      - name: show content
        run: echo "Hello ${{ steps.example-gist.outputs.content }}" > md5.txt
      - name: run bash script
        run: |
          cat md5.txt
          echo ff >> md5.txt
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.SEC_TOKEN }}
          gist_id: https://gist.github.com/Eloco/51ecb4c20767e5326ba1a5323a42a631
          gist_file_name: md5.txt
          file_path: ./md5.txt

      - name: Increment
        id: increment
        run: |
          cat md5.txt
          echo "::set-output name=value::`cat md5.txt`"

      - uses: sergeysova/gist-write-action@v1
        with:
          gist_id: 51ecb4c20767e5326ba1a5323a42a631
          file_name: md5.txt
          content: ${{steps.increment.outputs.value}}
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}
