name: 'github-to-gitee'

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'action'  
  schedule:
    - cron:  '00 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee. (git push -f)
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/Eloco
        dst: gitee/eloco
        dst_key:   ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN       }}
        force_update: true
        timeout: '1h'
        black_list: "BILIBILI-HELPER,terminal-note,eloco-note"
