name: 'misc_playwrigt_matrix'

on:
  workflow_dispatch:
    inputs:
        ignore_md5:
          description: 'if ignore md5 filter'  
          required: true
          default: 'false'
  schedule:
    - cron:  '*/20 * * * *'

jobs:
  shell:
    runs-on: ubuntu-latest
    env:
      gist_id : 3fd32567b6c8f6c79808905de208e59a
      repo_name  : Eloco/Sec-action-playwright-aws-md5
      ignore_md5: ${{ github.event.inputs.ignore_md5 }}
      repo_token : SEC_TOKEN
    strategy:
      matrix:
       include:
         - script: script/sec_playwright_news.py
           script_name: sec_playwright_news
           slack_hook: B0440LT1N65/0PCN09n6w8EdOg5V65shlcPx #hacker-idea
           FILE_BASE: message
           IF_PLAYWRIGHT: True
         - script: script/sci_math_playwright_news.py
           script_name: sci_math_playwright_news
           slack_hook: B0437FDSB2B/OtSUH0qiMig5nN3FhPUiESV6 #sci-math
           FILE_BASE: message
           IF_PLAYWRIGHT: True
         - script: script/sci_phy_playwright_news.py
           script_name: sci_phy_playwright_news
           skype_id: 19:dc5daf5835d342bab4c4d1d1c277e5bc@thread.skype
           slack_hook: B043K3T8VFF/aelEUM8MqK7XfnaEIr3w1AK4 #sci-phy
           FILE_BASE: message
           IF_PLAYWRIGHT: True
         - script: script/sci_stuff_playwright_news.py
           script_name: sci_stuff_playwright_news
           slack_hook: B044BMPKSSU/GNbOn151Llnus6xCcaEGd4Yj #sci stuff
           FILE_BASE: message
           IF_PLAYWRIGHT: True
         - script: script/playwright_mark.py
           script_name: playwright_mark.py
           slack_hook: B043K2XCDUN/ojA0j6wPADasJ0DLwRpTC871 #mark-eloco
           FILE_BASE: message
           IF_PLAYWRIGHT: True
           
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          repository: '${{ env.repo_name  }}'
          token:      '${{ secrets[env.repo_token]  }}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
            find * -name '*.py' | grep -v "${{ matrix.script  }}" | xargs rm
            python -m pip install --upgrade pip
            pip install pipreqs
            pip install fire
            pipreqs .
            pip install -r requirements.txt
        env:
            MATRIX_SCRIPT: ${{matrix.script}}

      - name: Install Playwright
        if: ${{ env.IF_PLAYWRIGHT  == 'True'}}
        run: |
            pip install playwright
            python -m playwright install
        env:
            IF_PLAYWRIGHT: ${{ matrix.IF_PLAYWRIGHT }}

      - name: run python downloader
        run: |
            export command="python ${{ matrix.script  }} 2>/dev/null"
            $command || $command  #retry command twice 

      - name: md5_count
        if  :  env.ignore_md5 != 'true'
        run: |
            wget https://raw.githubusercontent.com/Eloco/action-playwright-aws-md5/main/script/gist_md5.py
            wget https://gist.githubusercontent.com/Eloco/${{env.gist_id}}/raw/${{matrix.script_name}} -O md5.txt || echo "first init" > md5.txt 
            files_num=`python gist_md5.py --file_md5="./md5.txt" --file_dir=${{ matrix.FILE_BASE }}`
            echo $files_num
            echo 'FILE_NUM=${files_num}' >> ${GITHUB_OUTPUT}
            wc -l md5.txt
        id: gist-md5

      - name: gist-sync
        if  :  steps.gist-md5.outputs.FILE_NUM != '0' && env.ignore_md5 != 'true'
        uses: exuanbo/actions-deploy-gist@v1
        continue-on-error: true
        with:
          token: ${{ secrets.SEC_TOKEN }}
          gist_id: ${{env.gist_id}}
          gist_file_name: ${{matrix.script_name}}
          gist_description: ${{matrix.script_name}}
          file_path: md5.txt

      - name: send slack
        continue-on-error: true
        if  : steps.gist-md5.outputs.FILE_NUM != '0' || env.ignore_md5 == 'true'
        run: |
            wget https://raw.githubusercontent.com/Eloco/action-playwright-aws-md5/main/script/slack_sendMsg.py -O sendMsg.py
            msgPath=${{ matrix.FILE_BASE }} Hook="${{ matrix.slack_hook  }}" secHook=${{ secrets.SLACK_1 }} python sendMsg.py

      #- name: send skype
      #  continue-on-error: true
      #  uses: Eloco/docker-action-send-skype@v2
      #  if  : steps.gist-md5.outputs.FILE_NUM != '0'
      #  with:
      #      skype_username : ${{ secrets.SKYPE_MINE_USERNAME }}
      #      skype_password : ${{ secrets.SKYPE_MINE_PASSWORD }}
      #      skype_ids      : ${{ matrix.skype_id  }}
      #      send_msg_path  : ${{ matrix.FILE_BASE }}
      #      send_file_path : none
