name: 'misc_monitor_internet'

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'action'  
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  shell:
    runs-on: ubuntu-latest
    env:
      gist_id : 3fd32567b6c8f6c79808905de208e59a
      repo_name  : Eloco/Sec-action-playwright-aws-md5
      repo_token : SEC_TOKEN
    strategy:
      matrix:
       include:
         - script: script/playwright_monitor_github_topic.py
           script_name: playwright_monitor_github_topic.py
           skype_id: 19:6597e8c0288946c780660396d59929e3@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: True
         - script: script/playwright_monitor_internet.py
           script_name: playwright_monitor_internet.py
           skype_id: 19:9b2289cb130241f49a727ec6d6cd70f7@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: True
         - script: script/rss/rss_monitor.py
           script_name: rss_monitor.py
           skype_id: 19:842c94638f7543839cecd1ad75ed4dae@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: False
         - script: script/rss/secrss_monitor.py
           script_name: secrss_monitor.py
           skype_id: 19:4aed64355c2e4d409906c2a8946c7ec2@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: False
         - script: script/rss/animerss_monitor.py
           script_name: animerss_monitor.py
           skype_id: 19:84a74dce67f241b189c5a657828d57d8@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: False
         - script: script/rss/highfreq_monitor.py
           script_name: highfreq_monitor.py
           skype_id: 19:9221880a6d3c4274b7256deff420629c@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: False
         - script: script/rss/lowfreq_monitor.py
           script_name: lowfreq_monitor.py
           skype_id: 19:1aff469494654be8a854f36cbb68d7ec@thread.skype
           FILE_BASE: message
           IF_PLAYWRIGHT: False
           
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          repository: '${{ env.repo_name  }}'
          token:      '${{ secrets[env.repo_token]  }}'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
            find * -name '*.py' | grep -v "${{ matrix.script  }}" | xargs rm
            python -m pip install --upgrade pip
            pip install pipreqs
            pip install fire
            pipreqs .
            pip install -r requirements.txt
        env:
            MATRIX_SCRIPT: ${{matrix.script}}

      - name: Install Playwright
        if: ${{ env.IF_PLAYWRIGHT  == 'True'}}
        run: |
            pip install playwright
            python -m playwright install
        env:
            IF_PLAYWRIGHT: ${{ matrix.IF_PLAYWRIGHT }}

      - name: run python downloader
        run: |
            export command="python ${{ matrix.script  }} 2>/dev/null"
            $command || $command  #retry command twice 

      - name: gist-read
        uses: sergeysova/gist-read-action@v1
        id: example-gist
        continue-on-error: true
        with:
          gist_id: ${{env.gist_id}}
          file_name: ${{matrix.script_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}

      - name: md5_count
        run: |
            wget https://raw.githubusercontent.com/Eloco/action-playwright-aws-md5/main/script/gist_md5.py
            echo "${{ steps.example-gist.outputs.content }}" > md5.txt || echo "first init" > md5.txt 
            files_num=`python gist_md5.py --file_md5="./md5.txt" --file_dir=${{ matrix.FILE_BASE }}`
            echo $files_num
            echo '::set-output name=FILE_NUM::'$files_num
            head md5.txt
        id: gist-md5

      - uses: popsiclestick/gist-sync-action@v1.2.0
        if  :  steps.gist-md5.outputs.FILE_NUM != '0'
        with:
          auth: ${{ secrets.SEC_TOKEN }}
          gist_url: https://gist.github.com/Eloco/${{env.gist_id}}
          gist_title: ${{matrix.script_name}}
          gist_description: ${{matrix.script_name}}
          github_file: md5.txt

      - name: send skype
        continue-on-error: true
        uses: Eloco/docker-action-send-skype@v2
        if  : steps.gist-md5.outputs.FILE_NUM != '0'
        with:
            skype_username : ${{ secrets.SKYPE_MINE_USERNAME }}
            skype_password : ${{ secrets.SKYPE_MINE_PASSWORD }}
            skype_ids      : ${{ matrix.skype_id  }}
            send_msg_path  : ${{ matrix.FILE_BASE }}
            send_file_path : none
