name: 'sec_mail_monitor'

on:
  workflow_dispatch:
    inputs:
        ignore_md5:
          description: 'if ignore md5 filter'  
          required: true
          default: 'false'
  schedule:
    - cron:  '*/10 * * * *'
      #push:


jobs:
  main:
    runs-on: ubuntu-latest
    env:
      gist_id : 3fd32567b6c8f6c79808905de208e59a
      ignore_md5: ${{ github.event.inputs.ignore_md5 }}
    strategy:
      matrix:
       include:
         #- mail_user: WORK_OUTLOOK_USER
         #  mail_pass: WORK_OUTLOOK_KEY
         #  mail_server: 'outlook.office365.com'
         #  mail_box: 'INBOX'
         #  script_name: work_outlook
         #  send_skype_ids: '19:b690a79c04204eb49af0d745893a2d95@thread.skype'
         - mail_user: MINE_GMAIL_USER
           mail_pass: MINE_GMAIL_KEY
           mail_server: 'imap.gmail.com'
           mail_box: 'INBOX'
           #mail_box: 'Important'
           script_name: mine_gmail
           FILE_BASE: download
           slack_hook: B0440QF3LTB/4IZATHoaSGj2ACS52Momod8O #mail-gmail

    steps:
      - name: download script
        run: |
            wget https://github.com/Eloco/action-playwright-aws-md5/raw/main/mail/pyMail.py
            wget https://github.com/Eloco/action-playwright-aws-md5/raw/main/mail/mail_normal.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

          #- name: set cn-lang
          #  run: |
          #      sudo apt-get install fonts-wqy-zenhei
          #  continue-on-error: true

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pipreqs
            pipreqs .
            pip install -r requirements.txt

      - name: run python downloader
        continue-on-error: true
        run: |
            export MAIL_USER="${{secrets[matrix.mail_user]}}"
            export MAIL_PASS="${{secrets[matrix.mail_pass]}}"
            export MAIL_SERVER="${{matrix.mail_server}}"
            export MAIL_BOX="${{matrix.mail_box}}"
            python mail_normal.py

      - name: md5_count
        if  :  env.ignore_md5 != 'true'
        run: |
            wget https://raw.githubusercontent.com/Eloco/action-playwright-aws-md5/main/script/gist_md5.py
            pip install fire
            wget https://gist.githubusercontent.com/Eloco/${{env.gist_id}}/raw/${{matrix.script_name}} -O md5.txt || echo "first init" > md5.txt 
            files_num=`python gist_md5.py --file_md5="./md5.txt" --file_dir=${{ matrix.FILE_BASE }}`
            echo $files_num
            echo 'FILE_NUM=${files_num}' >> ${GITHUB_OUTPUT}
            wc -l md5.txt
        id: gist-md5

      - name: gist-sync
        if  :  steps.gist-md5.outputs.FILE_NUM != '0' && env.ignore_md5 != 'true'
        uses: exuanbo/actions-deploy-gist@v1
        continue-on-error: true
        with:
          token: ${{ secrets.SEC_TOKEN }}
          gist_id: ${{env.gist_id}}
          gist_file_name: ${{matrix.script_name}}
          gist_description: ${{matrix.script_name}}
          file_path: md5.txt

      - name: send slack
        continue-on-error: true
        if  : steps.gist-md5.outputs.FILE_NUM != '0' || env.ignore_md5 == 'true'
        run: |
            wget https://raw.githubusercontent.com/Eloco/action-playwright-aws-md5/main/script/slack_sendMsg.py -O sendMsg.py
            msgPath=${{ matrix.FILE_BASE }} Hook="${{ matrix.slack_hook  }}" secHook=${{ secrets.SLACK_1 }} python sendMsg.py
